function ListBuildings( keys )
	--DeepPrintTable(keys)
	--print ("Ability Name = " .. keys.ability:GetOwnerEntity())
	--DeepPrintTable(keys.ability:GetOwnerEntity())
	--if keys.ability:IsAlive() then print("yep") end
	--if keys.caster:HasAbility("repair") then print("CHUUU CHUU MOTHER FUCKER") end
	--keys.caster:FindAbilityByName("repair"):SetLevel(0)
	--print ("Mana regen = " .. keys.ability.FDesc.GetAbilityName)
	--[[
	local owner = keys.GetOwnerEntity()
	if (owner.FindAbilityByName("repair")) then print("found ability repair") end
	--print(keys.ability:GetAbilityName())
	--if (entity:FindAbilityByName("repair")) then print("found ability repair") end ]]
	keys.caster:RemoveAbility("antimage_blink")
	keys.caster:RemoveAbility("repair")
	keys.caster:RemoveAbility("shield")
	keys.caster:RemoveAbility("lone_druid_spirit_bear_entangle")
	keys.caster:RemoveAbility("death_prophet_silence")
	keys.caster:RemoveAbility("buildings")
	print("spells removed")
	keys.caster:AddAbility("build_rock")
	keys.caster:AddAbility("build_house")
	keys.caster:AddAbility("build_tower")
	keys.caster:AddAbility("build_castle")
	keys.caster:AddAbility("navigation_right")
	keys.caster:AddAbility("navigation_back")
	keys.caster:FindAbilityByName("build_rock"):SetLevel(1)
	keys.caster:FindAbilityByName("build_house"):SetLevel(1)
	keys.caster:FindAbilityByName("build_tower"):SetLevel(1)
	keys.caster:FindAbilityByName("build_castle"):SetLevel(1)
	keys.caster:FindAbilityByName("navigation_right"):SetLevel(1)
	keys.caster:FindAbilityByName("navigation_back"):SetLevel(1)
	print("frist page of buildings ready")
end

function TurnRight( keys )
	keys.caster:RemoveAbility("build_rock")
	keys.caster:RemoveAbility("build_house")
	keys.caster:RemoveAbility("build_tower")
	keys.caster:RemoveAbility("build_castle")
	keys.caster:RemoveAbility("navigation_right")
	print("frist page of buildings removed")
	keys.caster:AddAbility("build_guild")
	keys.caster:AddAbility("build_tree")
	keys.caster:AddAbility("build_lab")
	keys.caster:AddAbility("build_true_tower")
	keys.caster:AddAbility("navigation_left")
	keys.caster:FindAbilityByName("build_guild"):SetLevel(1)
	keys.caster:FindAbilityByName("build_tree"):SetLevel(1)
	keys.caster:FindAbilityByName("build_lab"):SetLevel(1)
	keys.caster:FindAbilityByName("build_true_tower"):SetLevel(1)
	keys.caster:FindAbilityByName("navigation_left"):SetLevel(1)
	print("second page of buildings ready")
end

function TurnLeft( keys )
	keys.caster:RemoveAbility("build_guild")
	keys.caster:RemoveAbility("build_tree")
	keys.caster:RemoveAbility("build_lab")
	keys.caster:RemoveAbility("build_true_tower")
	keys.caster:RemoveAbility("navigation_left")
	print("second page of buildings removed")
	keys.caster:AddAbility("build_rock")
	keys.caster:AddAbility("build_house")
	keys.caster:AddAbility("build_tower")
	keys.caster:AddAbility("build_castle")
	keys.caster:AddAbility("navigation_right")
	keys.caster:FindAbilityByName("build_rock"):SetLevel(1)
	keys.caster:FindAbilityByName("build_house"):SetLevel(1)
	keys.caster:FindAbilityByName("build_tower"):SetLevel(1)
	keys.caster:FindAbilityByName("build_castle"):SetLevel(1)
	keys.caster:FindAbilityByName("navigation_right"):SetLevel(1)
	print("frist page of buildings ready")
end

function BackToSpells( keys )
	if keys.caster:HasAbility("build_rock")
	then
		keys.caster:RemoveAbility("build_rock")
		keys.caster:RemoveAbility("build_house")
		keys.caster:RemoveAbility("build_tower")
		keys.caster:RemoveAbility("build_castle")
		keys.caster:RemoveAbility("navigation_right")
		keys.caster:RemoveAbility("navigation_back")
		print("frist page of buildings removed")
	else
		keys.caster:RemoveAbility("build_guild")
		keys.caster:RemoveAbility("build_tree")
		keys.caster:RemoveAbility("build_lab")
		keys.caster:RemoveAbility("build_true_tower")
		keys.caster:RemoveAbility("navigation_left")
		keys.caster:RemoveAbility("navigation_back")
		print("second page of buildings removed")
	end

	keys.caster:AddAbility("antimage_blink")
	keys.caster:AddAbility("repair")
	keys.caster:AddAbility("shield")
	keys.caster:AddAbility("lone_druid_spirit_bear_entangle")
	keys.caster:AddAbility("death_prophet_silence")
	keys.caster:AddAbility("buildings")
	keys.caster:FindAbilityByName("antimage_blink"):SetLevel(1)
	keys.caster:FindAbilityByName("repair"):SetLevel(1)
	keys.caster:FindAbilityByName("shield"):SetLevel(1)
	keys.caster:FindAbilityByName("lone_druid_spirit_bear_entangle"):SetLevel(1)
	keys.caster:FindAbilityByName("death_prophet_silence"):SetLevel(1)
	keys.caster:FindAbilityByName("buildings"):SetLevel(1)
	print("spells ready")
end